#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source .env.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/.env" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/.env"
fi

# Source sensitive aliases.
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zsh_debian"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zsh_macos"
else
    echo "Unknown OS type: $OSTYPE"
fi

# Source any shared config
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zsh_shared" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zsh_shared"
fi

# Aliases
# I store non-sensitive aliases here, but keep any sensitive aliases in a
# separate file, so I don't have to commit it to source control.

# Utility
alias myip="curl http://ipecho.net/plain; echo"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
